### ISSUE TITLE
DataLoader worker (pid xxxx) is killed by signal

### ISSUE THREAD

**Issue by Zhendong-Wang** [NVlabs/edm#7]
Hi there, thanks for sharing another good code base. Recently I keep receving the dataloader killing error when I run experiments on ImageNet dataset after certain iterations. I tried several times and it always happens after a duration (~15h). 

The code run well for other datasets but only failed on ImageNet dataset. The ImageNet dataset should be fine since I have run other experiments onto it and didn't find similar issues. Not sure what happened here and hope this can be solved. 

I provide the error log below. 

```
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "/opt/miniconda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 229, in main
    training_loop.training_loop(**c)
  File "/root/code/Text2Image-DiT/training/training_loop.py", line 156, in training_loop
    torch.nan_to_num(param.grad, nan=0, posinf=1e5, neginf=-1e5, out=param.grad)
  File "/opt/miniconda/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1680) is killed by signal: Killed.
```

Thanks in advance!

**Comment by Zhendong-Wang** [comment]
Found the issue was caused by CPU memeory limit.
